/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DangerButton: typeof import('./src/components/Button/DangerButton.vue')['default']
    DarkButtonLink: typeof import('./src/components/Button/DarkButtonLink.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/Dropdown.vue')['default']
    DropdownItem: typeof import('./src/components/Dropdown/DropdownItem.vue')['default']
    EditorButton: typeof import('./src/components/Button/EditorButton.vue')['default']
    Layout: typeof import('./src/components/Layouts/Layout.vue')['default']
    Logo: typeof import('./src/components/DataDisplay/Logo.vue')['default']
    MenuDelimiter: typeof import('./src/components/Sidebar/MenuDelimiter.vue')['default']
    MenuGroupBody: typeof import('./src/components/Sidebar/MenuGroupBody.vue')['default']
    MenuGroupHeader: typeof import('./src/components/Sidebar/MenuGroupHeader.vue')['default']
    MenuItem: typeof import('./src/components/Sidebar/MenuItem.vue')['default']
    NavBar: typeof import('./src/components/Navigation/NavBar.vue')['default']
    Notifications: typeof import('./src/components/Util/Notifications.vue')['default']
    Pagination: typeof import('./src/components/Navigation/Pagination.vue')['default']
    PrimaryButton: typeof import('./src/components/Button/PrimaryButton.vue')['default']
    PureButton: typeof import('./src/components/Button/PureButton.vue')['default']
    PureButtonLink: typeof import('./src/components/Button/PureButtonLink.vue')['default']
    PureDangerButton: typeof import('./src/components/Button/PureDangerButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/components/Button/SecondaryButton.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar/Sidebar.vue')['default']
    Tab: typeof import('./src/components/Navigation/Tab.vue')['default']
    Tabs: typeof import('./src/components/Navigation/Tabs.vue')['default']
    UserMenu: typeof import('./src/components/Navigation/UserMenu.vue')['default']
    WarningButton: typeof import('./src/components/Button/WarningButton.vue')['default']
  }
}
